<?php

namespace SIGTASBundle\Repository;

/**
 * AssessementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessementRepository extends \Doctrine\ORM\EntityRepository
{
}
