<?php

namespace SIGTASBundle\Repository;

/**
 * AssessmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssessmentRepository extends \Doctrine\ORM\EntityRepository
{
}
