<?php

namespace SIGTASBundle\Repository;

/**
 * AssujettissmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssujettissmentRepository extends \Doctrine\ORM\EntityRepository
{
}
