<?php

namespace SIGTASBundle\Repository;

/**
 * DocAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocAmountRepository extends \Doctrine\ORM\EntityRepository
{
}
