<?php

namespace SIGTASBundle\Repository;

/**
 * DocCourrierTitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocCourrierTitreRepository extends \Doctrine\ORM\EntityRepository
{
}
