<?php

namespace SIGTASBundle\Repository;

/**
 * DocCourrierObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocCourrierObjetRepository extends \Doctrine\ORM\EntityRepository
{
}
