<?php

namespace SIGTASBundle\Repository;

/**
 * FiscalRegimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiscalRegimeRepository extends \Doctrine\ORM\EntityRepository
{
}
