<?php

namespace SIGTASBundle\Repository;

/**
 * PAIEMENTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PAIEMENTRepository extends \Doctrine\ORM\EntityRepository
{
 public function selectAll($contribuable_nif)
    {
        return $this->createQueryBuilder('carte')
            ->andWhere('carte.nif = :val')
            ->setParameter('val', $contribuable_nif)
            ->getQuery()
            ->getArrayResult()
        ;
}
}
