<?php

namespace SIGTASBundle\Repository;

/**
 * RAR_PERIODERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RAR_PERIODERepository extends \Doctrine\ORM\EntityRepository
{
}
