<?php

namespace SIGTASBundle\Repository;

/**
 * SECTOR_ACTIVITYRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SECTOR_ACTIVITYRepository extends \Doctrine\ORM\EntityRepository
{
}
