<?php

namespace SIGTASBundle\Repository;

/**
 * SectorActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
