<?php

namespace SIGTASBundle\Repository;

/**
 * TAX_ACCOUNTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TAX_ACCOUNTRepository extends \Doctrine\ORM\EntityRepository
{
}
