<?php

namespace SIGTASBundle\Repository;

/**
 * TaxationOfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxationOfficeRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectAll($contribuable_nif)
    {
        return $this->createQueryBuilder('carte')
            ->andWhere('carte.nif = :val')
            ->setParameter('val', $contribuable_nif)
            ->getQuery()
            ->getArrayResult()
        ;
    }
}
