<?php

namespace DBundle\Repository;

/**
 * AnnexeTvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnexeTvaRepository extends \Doctrine\ORM\EntityRepository
{
}
