<?php

namespace DBundle\Repository;

/**
 * AssujettissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssujettissementRepository extends \Doctrine\ORM\EntityRepository
{
}
