<?php

namespace DBundle\Repository;

/**
 * CategorieCourierEntrantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieCourierEntrantRepository extends \Doctrine\ORM\EntityRepository
{
}
