<?php

namespace DBundle\Repository;

/**
 * CategorieCourierSortantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieCourierSortantRepository extends \Doctrine\ORM\EntityRepository
{
}
