<?php

namespace DBundle\Repository;

/**
 * Dfu_objetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContribuablesDfuObjetRepository extends \Doctrine\ORM\EntityRepository
{
}
