<?php

namespace DBundle\Repository;

/**
 * CourierEntrantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourierEntrantRepository extends \Doctrine\ORM\EntityRepository
{
}
