<?php

namespace DBundle\Repository;

/**
 * CourrierDispatchingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourrierDispatchingRepository extends \Doctrine\ORM\EntityRepository
{
}
