<?php

namespace DBundle\Repository;

/**
 * CourierSortantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourierSortantRepository extends \Doctrine\ORM\EntityRepository
{
}
