<?php

namespace DBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclarationsRepository extends \Doctrine\ORM\EntityRepository
{
}
