<?php

namespace DBundle\Repository;

/**
 * DgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DgeRepository extends \Doctrine\ORM\EntityRepository
{
}
