<?php

namespace DBundle\Repository;

/**
 * DocCourrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocCourrierRepository extends \Doctrine\ORM\EntityRepository
{
}
