<?php

namespace DBundle\Repository;

/**
 * DossiersSQVFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossiersSQVFRepository extends \Doctrine\ORM\EntityRepository
{
  public function dosTruncate()
  {
    $conn = $this->getEntityManager()->getConnection();
    $sql = "SET FOREIGN_KEY_CHECKS = 0;
            TRUNCATE TABLE DossiersSQVF;
            ";
    $stmt = $conn->prepare($sql);
    return $stmt->execute();
  }

}
