<?php

namespace DBundle\Repository;

/**
 * DossiersAnneeControleMontantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossiersAnneeControleMontantRepository extends \Doctrine\ORM\EntityRepository
{
}
