<?php

namespace DBundle\Repository;

/**
 * DossiersAnneeControleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossiersAnneeControleRepository extends \Doctrine\ORM\EntityRepository
{
}
