<?php

namespace DBundle\Repository;

/**
 * EntrantObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrantObjetRepository extends \Doctrine\ORM\EntityRepository
{
}
