<?php

namespace DBundle\Repository;

/**
 * filexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class filexRepository extends \Doctrine\ORM\EntityRepository
{
}
