<?php

namespace DBundle\Repository;

/**
 * GestionnaireCourrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionnaireCourrierRepository extends \Doctrine\ORM\EntityRepository
{
  public function deleteAll()
  {
    $conn = $this->getEntityManager()
      ->getConnection();
    $sql = "SET FOREIGN_KEY_CHECKS = 0;
        TRUNCATE TABLE gestionnaireCourrier;
        SET FOREIGN_KEY_CHECKS = 1";
    $stmt = $conn->prepare($sql);

    return $stmt->execute();
  }
}
