<?php

namespace DBundle\Repository;

/**
 * InfosSupplementaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosSupplementaireRepository extends \Doctrine\ORM\EntityRepository
{
}
