<?php

namespace DBundle\Repository;

/**
 * MissionObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionObservationRepository extends \Doctrine\ORM\EntityRepository
{
}
