<?php

namespace DBundle\Repository;

/**
 * MissionObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionObjetRepository extends \Doctrine\ORM\EntityRepository
{
}
