<?php

namespace DBundle\Repository;

/**
 * PourInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PourInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
