<?php

namespace DBundle\Repository;

/**
 * RARSANSPERIODERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RARSANSPERIODERepository extends \Doctrine\ORM\EntityRepository
{
}
