<?php

namespace DBundle\Repository;

/**
 * RelanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelanceRepository extends \Doctrine\ORM\EntityRepository
{
}
