<?php

namespace DBundle\Repository;

/**
 * RelanceSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelanceSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
