<?php

namespace DBundle\Repository;

/**
 * SaiSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaiSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
