<?php

namespace DBundle\Repository;

/**
 * SortantObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortantObjetRepository extends \Doctrine\ORM\EntityRepository
{
}
