<?php

namespace DBundle\Repository;

/**
 * sqvfDossiersAnneeControleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvfDossiersAnneeControleRepository extends \Doctrine\ORM\EntityRepository
{
}
