<?php

namespace DBundle\Repository;

/**
 * sqvfNifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvfNifRepository extends \Doctrine\ORM\EntityRepository
{
}
