<?php

namespace DBundle\Repository;

/**
 * sqvfDossiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvfDossiersRepository extends \Doctrine\ORM\EntityRepository
{
}
