<?php

namespace DBundle\Repository;

/**
 * SuiviCourrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviCourrierRepository extends \Doctrine\ORM\EntityRepository
{
}
