<?php

namespace DBundle\Repository;

/**
 * SuiviDossiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviDossiersRepository extends \Doctrine\ORM\EntityRepository
{
}
