<?php

namespace DBundle\Repository;

/**
 * tax_familleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tax_familleRepository extends \Doctrine\ORM\EntityRepository
{
}
