<?php

namespace DBundle\Repository;

/**
 * tax_famille_childRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tax_famille_childRepository extends \Doctrine\ORM\EntityRepository
{
}
