<?php

namespace DBundle\Repository;

/**
 * TypeDeDossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDeDossierRepository extends \Doctrine\ORM\EntityRepository
{
}
