<?php

namespace DBundle\Repository;

/**
 * TypeDossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDossierRepository extends \Doctrine\ORM\EntityRepository
{
}
