<?php

namespace DBundle\Repository;

/**
 * userSQVFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userSQVFRepository extends \Doctrine\ORM\EntityRepository
{
}
