<?php

namespace DBundle\Repository;

/**
 * VerificationsEnCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerificationsEnCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
