d_annexe_tva:
    resource: "@DBundle/Controller/AnnexeTvaController.php"
    type:     annotation

d_suivi_dossiers:
    resource: "@DBundle/Controller/SuiviDossiersController.php"
    type:     annotation

sigtas:
    resource: "@SIGTASBundle/Resources/config/routing.yml"
    prefix:   /sigtas

nif:
    resource: "@NIFBundle/Resources/config/routing.yml"
    prefix:   /nif

d:
    resource: "@DBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

avanzu_admin:
    prefix: / # or whichever you like 
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"

# avanzu_admin_home:
#   path: /accueil/
#   defaults: {_controller: DBundle:Default:index}
#   options:
#     avanzu_admin_route: accueil


avanzu_admin_home:
  path: /home
  defaults: {_controller: DBundle:CourierEntrant:List }
  options:
    avanzu_admin_route: accueil

# app_entrantGen:
#     path:     /entrantGen
#     defaults: { _controller: AppBundle:Genesis:entrantGen }

# app_enterpriseGen:
#     path:     /enterpriseGen
#     defaults: { _controller: AppBundle:Genesis:enterpriseGen }

# app_taxpayerGen:
#     path:     /taxpayerGen
#     defaults: { _controller: AppBundle:Genesis:index }