<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_dossiers_referencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_dossiers_referencesRepository extends \Doctrine\ORM\EntityRepository
{
}
