<?php

namespace SQVFBundle\Repository;

/**
 * DocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_documentsRepository extends \Doctrine\ORM\EntityRepository
{
}
