<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_agents_verificateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_dossiers_agent_verificateurRepository extends \Doctrine\ORM\EntityRepository
{
}
