<?php

namespace SQVFBundle\Repository;

/**
 * TypeNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_type_notificationRepository extends \Doctrine\ORM\EntityRepository
{
}
