<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_type_impotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_type_impotsRepository extends \Doctrine\ORM\EntityRepository
{
}
