<?php

namespace SQVFBundle\Repository;

/**
 * TypeNotifDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_type_notification_definitiveRepository extends \Doctrine\ORM\EntityRepository
{
}
