<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_categories_groupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_categories_groupsRepository extends \Doctrine\ORM\EntityRepository
{
}
