<?php

namespace SQVFBundle\Repository;

/**
 * TypeNotifRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_type_notification_redressementRepository extends \Doctrine\ORM\EntityRepository
{
}
