<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_documents_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_documents_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
