<?php

namespace SQVFBundle\Repository;

/**
 * NifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_nifRepository extends \Doctrine\ORM\EntityRepository
{
}
