<?php

namespace SQVFBundle\Repository;

/**
 * DossiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_dossiersRepository extends \Doctrine\ORM\EntityRepository
{
}
