<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_admin_menuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_admin_menuRepository extends \Doctrine\ORM\EntityRepository
{
}
