<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_dossiers_annulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_dossiers_annulesRepository extends \Doctrine\ORM\EntityRepository
{
}
