<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_dossiers_annee_controle_base_utiliseeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_dossiers_annee_controle_base_utiliseeRepository extends \Doctrine\ORM\EntityRepository
{
}
