<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_dossiers_annee_controle_document_consulte_apres_annulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_dossiers_annee_controle_document_consulte_apres_annulationRepository extends \Doctrine\ORM\EntityRepository
{
}
