<?php

namespace SQVFBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_usersRepository extends \Doctrine\ORM\EntityRepository
{
}
