<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_categoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_categoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
