<?php

namespace SQVFBundle\Repository;

/**
 * DocumentsFichiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_documents_fichiersRepository extends \Doctrine\ORM\EntityRepository
{
}
