<?php

namespace SQVFBundle\Repository;

/**
 * sqvf_centre_fiscalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sqvf_centre_fiscalRepository extends \Doctrine\ORM\EntityRepository
{
}
