new_entrant:
    path:     entrant/new
    defaults: { _controller: DBundle:Entrant:new }

list_entrant:
    path:     entrant/list
    defaults: { _controller: DBundle:Entrant:list }

list_entrant_dispatch:
    path:     entrant/listeDispatch
    defaults: { _controller: DBundle:Entrant:listDispatch }

list_entrant_all:
    path:     entrant/listeAll
    defaults: { _controller: DBundle:Entrant:listAll }

list_entrant_sce:
    path:     entrant/listeAllService
    defaults: { _controller: DBundle:Entrant:listAllService }

list_entrant_all_others:
    path:     entrant/listeAllOthers
    defaults: { _controller: DBundle:Entrant:listAllOthers }

list_entrant_assigne:
    path:     entrant/listeAssigne
    defaults: { _controller: DBundle:Entrant:listAssigne }

list_entrant_assigne_all:
    path:     entrant/listeAssigneAll
    defaults: { _controller: DBundle:Entrant:listAssigneAll }

addobs_nontraite:
    path:     entrant/addObsNonTraite
    defaults: { _controller: DBundle:Entrant:addObsNonTraite }

show_entrant:
    path:     entrant/show/{courrier}
    defaults: { _controller: DBundle:Entrant:show }
   # requirements:
    #    id: \d+

new_entrant_cat:
    path:     entrant/cat/new
    defaults: { _controller: DBundle:Entrant:newCat }

list_entrant_cat:
    path:     entrant/cat/liste
    defaults: { _controller: DBundle:Entrant:listCat }

edit_entrant_cat:
    path:     entrant/cat/edit/{nature}
    defaults: { _controller: DBundle:Entrant:editCat }
    requirements:
        id: \d+

_entrant_dispatching_to_service:
    path:     /couriers/entrant/dispatching/courrier/{courrier}/to/service/{service}
    defaults: { _controller: DBundle:Entrant:dispatchToService }

_entrant_informatice_to_service:
    path:     /couriers/entrant/informative/courrier/{courrier}/to/service/{service}
    defaults: { _controller: DBundle:Entrant:forInfoToService }

_entrant_dispatching_to_gestionnaire:
    path:     /couriers/entrant/dispatching/courrier/{courrier}/to/gestionnaire/{gestionnaire}
    defaults: { _controller: DBundle:Entrant:dispatchToGestionnaire }

_entrant_get:
    path:     /couriers/entrant/courrier/get/{courrier}
    defaults: { _controller: DBundle:Entrant:getCourrier }

_entrant_close:
    path:     /couriers/entrant/close/{courrier}
    defaults: { _controller: DBundle:Entrant:cloturerTicket }

_entrant_marquer_comme_traiter:
    path:     /couriers/entrant/marquer/comme/traiter/{courrier}
    defaults: { _controller: DBundle:Entrant:marquerCommeTraiter }

list_entrant_pdf:
    path:     Entrant/listPdf
    defaults: { _controller: DBundle:Entrant:listPdf }

list_entrant_dispatch_pdf:
    path:     Entrant/listDispatchPdf
    defaults: { _controller: DBundle:Entrant:listDispatchPdf }

list_entrant_all_pdf:
    path:     entrant/listeAllPdf
    defaults: { _controller: DBundle:Entrant:listAllPdf }

updatestatus:
    path:     tache/update/{courrier}
    defaults: { _controller: DBundle:Tache:TacheUpdate }

newobs:
    path:     tache/newObs/{courrier}
    defaults: { _controller: DBundle:Tache:NewObservation } 
    
stat_entrant_cat:
    path:     entrant/cat/stat
    defaults: { _controller: DBundle:Entrant:statCat }

stat_entrant_periode:
    path:     entrant/statParPeriode
    defaults: { _controller: DBundle:Entrant:statParPeriode }
