# missions
missions_add:
    path:     /missions/add
    defaults: { _controller: "DBundle:Missions:add" }
    methods:  [GET, POST]

new_mission:
    path:     mission/new
    defaults: { _controller: DBundle:Missions:new }

list_mission:
    path:     mission/liste
    defaults: { _controller: DBundle:Missions:list }

show_mission:
    path:     mission/show/{courrier}
    defaults: { _controller: DBundle:Missions:show }
    requirements:
        id: \d+

new_mission_cat:
    path:     mission/cat/new
    defaults: { _controller: DBundle:Missions:newCat }

list_mission_cat:
    path:     mission/cat/liste
    defaults: { _controller: DBundle:Missions:listCat }

edit_mission_cat:
    path:     mission/cat/edit/{nature}
    defaults: { _controller: DBundle:Missions:editCat }
    requirements:
        id: \d+

updatestatusM:
    path:     mission/update/{courrier}
    defaults: { _controller: DBundle:Missions:missionUpdate } 

nxobs:
    path:     mission/nxObs/{courrier}
    defaults: { _controller: DBundle:Missions:nxObservation } 
